version: '3.7'

x-volumes:
  &default-volume

services:
  cli:
    build:
      context: ./.docker
      dockerfile: Dockerfile.cli
    volumes:
    #  - ssh-volume:amazeeio-ssh-agent
      - app-volume:/app
    environment:
      - PATH=/app/vendor/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - HOME=/home/govcms
      - SSH_AUTH_SOCK=/tmp/amazeeio_ssh-agent/socket

volumes:
  ssh-volume:
  app-volume:
    driver: local
    driver_opts:
      type: none
      device: $PWD
      o: bind
